// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHi698OgnkIhqdOL9L8UeqpxAMlMi9z0',
    appId: '1:1050684194881:web:bd798e323e44d798ef46c0',
    messagingSenderId: '1050684194881',
    projectId: 'otherfirebaseflutter',
    authDomain: 'otherfirebaseflutter.firebaseapp.com',
    storageBucket: 'otherfirebaseflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPFHEDpql8oz5jPtBO5dKuSz_tQ7PPSlk',
    appId: '1:1050684194881:android:66ce86a47ca42cfeef46c0',
    messagingSenderId: '1050684194881',
    projectId: 'otherfirebaseflutter',
    storageBucket: 'otherfirebaseflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUz3Sa7oPlFM49tQQ1rHLyB18wHVwEHkU',
    appId: '1:1050684194881:ios:4c5c131b498e8a79ef46c0',
    messagingSenderId: '1050684194881',
    projectId: 'otherfirebaseflutter',
    storageBucket: 'otherfirebaseflutter.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUz3Sa7oPlFM49tQQ1rHLyB18wHVwEHkU',
    appId: '1:1050684194881:ios:72d2c0df0a880c14ef46c0',
    messagingSenderId: '1050684194881',
    projectId: 'otherfirebaseflutter',
    storageBucket: 'otherfirebaseflutter.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
